name: health_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  pinput: ^2.2.21
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  go_router: ^4.5.1
  url_strategy: ^0.2.0
  flutter_svg: ^1.1.6
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6
  table_calendar: ^3.0.8
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.3.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto/
    - assets/images/
    - assets/data/state_and_city.json
